- pipeline.id: netstat
  path.config: "/usr/share/logstash/pipeline/netstat.conf"
- pipeline.id: tasklist
  path.config: "/usr/share/logstash/pipeline/tasklist.conf"
- pipeline.id: usb
  path.config: "/usr/share/logstash/pipeline/USB.conf"